version: '3'

services:
  server:
    container_name: hacka-node
    build: '.'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'
    networks: 
      - meinveste-network

  db:
    image: 'mongo'
    container_name: hacka-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks: 
      - meinveste-network

  ngrok:
    image: wernight/ngrok
    command: ngrok http hacka-node:9000
    depends_on: 
      - "server"
    networks:
      - meinveste-network
    ports: 
      - 4040:4040

networks:
  meinveste-network:
    driver: bridge